spring.application.name=runnerz

#we can configure things related to our application here
#example: I want to run on localhost 3020 instead of 8080 , we will run
#server.port = 3020

spring.h2.console.enabled=true
spring.datasource.name = runnerz
spring.h2.console.path=/h2-console
spring.datasource.generate-unique-name=false