services:
  postgres:
    image: postgres:16

    container_name: first-postgres

    environment:
      POSTGRES_DB: first
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      TZ: UTC
      PGTZ: UTC

    ports:
      - "5432:5432"

    restart: unless-stopped